// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC__ioxarUUBttWq5j8zwWWussZm6HKqh4',
    appId: '1:737253877501:web:765235758218f072a44094',
    messagingSenderId: '737253877501',
    projectId: 'internquiz-a3fd0',
    authDomain: 'internquiz-a3fd0.firebaseapp.com',
    storageBucket: 'internquiz-a3fd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSxjrjM14DnlcDZB3KOlqvRFyZBczGrRM',
    appId: '1:737253877501:android:72a7b57f73f0b2a9a44094',
    messagingSenderId: '737253877501',
    projectId: 'internquiz-a3fd0',
    storageBucket: 'internquiz-a3fd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqj20oacC68d7CfjehtWHy-POjXtNeCfs',
    appId: '1:737253877501:ios:354839c57eb57e96a44094',
    messagingSenderId: '737253877501',
    projectId: 'internquiz-a3fd0',
    storageBucket: 'internquiz-a3fd0.appspot.com',
    iosBundleId: 'com.example.internQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqj20oacC68d7CfjehtWHy-POjXtNeCfs',
    appId: '1:737253877501:ios:354839c57eb57e96a44094',
    messagingSenderId: '737253877501',
    projectId: 'internquiz-a3fd0',
    storageBucket: 'internquiz-a3fd0.appspot.com',
    iosBundleId: 'com.example.internQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC__ioxarUUBttWq5j8zwWWussZm6HKqh4',
    appId: '1:737253877501:web:c5b3e194ce28d332a44094',
    messagingSenderId: '737253877501',
    projectId: 'internquiz-a3fd0',
    authDomain: 'internquiz-a3fd0.firebaseapp.com',
    storageBucket: 'internquiz-a3fd0.appspot.com',
  );
}
